import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import localFont from "next/font/local";
import Alert from "./components/alert/Alert";
import ClientDowntimeWrapper from "./components/alert/no_backend/ClientDowntimeWrapper";

/** Load Vazir font from local files */
const vazir = localFont({
  src: [
    {
      path: "../public/fonts/vazirmatn/Vazirmatn-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/vazirmatn/Vazirmatn-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-vazir",
});

/** Application metadata */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Root layout containing global structure, styling, and providers */
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl" className={vazir.variable}>
      <body className="font-sans bg-main-bg min-h-screen">
        {/* <Alert /> — enable for global announcements */}
        <Navbar />
        <ClientDowntimeWrapper>{children}</ClientDowntimeWrapper>
        <Footer />
      </body>
    </html>
  );
}
