import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Vazirmatn } from "next/font/google";


const vazir = Vazirmatn({
  subsets: ["arabic"], // includes Persian
  display: "swap",
});


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={vazir.className}>
        {children}
        </body>
    </html>
  );
}
